---
- when: reload4j_install_jar is defined
  block:
    - name: downloading {{ reload4j_url }} to {{ reload4j_install_jar }}
      become: true
      become_user: root
      get_url:
        url: '{{ reload4j_url }}'
        dest: '{{ reload4j_install_jar }}'
        checksum: '{{ reload4j_checksum }}'
        mode: 0644
